// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:peercoin/models/hive/app_options.dart';
import 'package:peercoin/models/hive/coin_wallet.dart';
import 'package:peercoin/models/hive/pending_notifications.dart';
import 'package:peercoin/models/hive/roast_wallet.dart';
import 'package:peercoin/models/hive/server.dart';
import 'package:peercoin/models/hive/wallet_address.dart';
import 'package:peercoin/models/hive/wallet_transaction.dart';
import 'package:peercoin/models/hive/wallet_utxo.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppOptionsStoreAdapter());
    registerAdapter(CoinWalletAdapter());
    registerAdapter(PendingNotificationAdapter());
    registerAdapter(ROASTWalletAdapter());
    registerAdapter(ServerAdapter());
    registerAdapter(WalletAddressAdapter());
    registerAdapter(WalletTransactionAdapter());
    registerAdapter(WalletUtxoAdapter());
  }
}
